### ISSUE TITLE
Setup SQL definition provider

### ISSUE THREAD

**Issue by breeky-dev** [EndGameGl/DotNetBungieAPI#4]
Hi,

First, thanks for this awesome library, it super useful and saves a lot of time.

I'm having a hard time finding out how to setup the DefinitionProvider.Sqlite. Below is what I wrote in Program.cs to setup the provider : 

```
bungieClient.DefinitionProvider.UseSqliteDefinitionProvider(definitionProvider =>
    {
        definitionProvider.ManifestFolderPath = "/My_Path";
        definitionProvider.AutoUpdateManifestOnStartup = true;
        definitionProvider.FetchLatestManifestOnInitialize = true;
        definitionProvider.DeleteOldManifestDataAfterUpdates = true;
    });
```

but I get the following error. Could you provide an example or more specific explanations in the wiki about how to setup an SQLite DB to make it work ?
Thanks

```
blazor.webassembly.js:1 
        
       crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.DllNotFoundException: e_sqlite3
   at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
   at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
   at SQLitePCL.Batteries_V2.Init()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.Data.Sqlite.SqliteConnection..cctor()
   --- End of inner exception stack trace ---
   at DotNetBungieAPI.DefinitionProvider.Sqlite.SqliteDefinitionProvider..ctor(IBungieClientConfiguration bungieClientConfiguration, SqliteDefinitionProviderConfiguration configuration, ILogger`1 logger, IBungieNetJsonSerializer serializer, IDestiny2MethodsAccess destiny2MethodsAccess, IDotNetBungieApiHttpClient httpClient, IDefinitionAssemblyData assemblyData)
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.DoInvoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Type, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Func`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(Type key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass7_0.<CreateInitializer>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateComponent(Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
window.Module.s.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 
        
       crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: No element is currently associated with component 19
      Error: No element is currently associated with component 19
          at se.updateComponent (https://localhost:7265/_framework/blazor.webassembly.js:1:19948)
          at https://localhost:7265/_framework/blazor.webassembly.js:1:57076
          at At.Fe._internal.renderBatch (https://localhost:7265/_framework/blazor.webassembly.js:1:57448)
          at Object.St [as invokeJSFromDotNet] (https://localhost:7265/_framework/blazor.webassembly.js:1:60134)
          at _mono_wasm_invoke_js_blazor (https://localhost:7265/_framework/dotnet.6.0.14.9j6y7g0hzq.js:1:195300)
          at wasm://wasm/00971dea:wasm-function[3308]:0xc6136
          at wasm://wasm/00971dea:wasm-function[167]:0xd602
          at wasm://wasm/00971dea:wasm-function[166]:0xbd73
          at wasm://wasm/00971dea:wasm-function[2815]:0xabef3
          at wasm://wasm/00971dea:wasm-function[1619]:0x6fcb4
Microsoft.JSInterop.JSException: No element is currently associated with component 19
Error: No element is currently associated with component 19
    at se.updateComponent (https://localhost:7265/_framework/blazor.webassembly.js:1:19948)
    at https://localhost:7265/_framework/blazor.webassembly.js:1:57076
    at At.Fe._internal.renderBatch (https://localhost:7265/_framework/blazor.webassembly.js:1:57448)
    at Object.St [as invokeJSFromDotNet] (https://localhost:7265/_framework/blazor.webassembly.js:1:60134)
    at _mono_wasm_invoke_js_blazor (https://localhost:7265/_framework/dotnet.6.0.14.9j6y7g0hzq.js:1:195300)
    at wasm://wasm/00971dea:wasm-function[3308]:0xc6136
    at wasm://wasm/00971dea:wasm-function[167]:0xd602
    at wasm://wasm/00971dea:wasm-function[166]:0xbd73
    at wasm://wasm/00971dea:wasm-function[2815]:0xabef3
    at wasm://wasm/00971dea:wasm-function[1619]:0x6fcb4
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object,Object](String identifier, Int32 arg0, RenderBatch arg1, Object arg2, Int64 targetInstanceId)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object](String identifier, Int32 arg0, RenderBatch arg1)
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.UpdateDisplayAsync(RenderBatch& batch)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

**Comment by EndGameGl** [comment]
@samuel-chp  Am I getting it right that you tried to use sqlite provider in Blazor clientside?
If so, it won't work, Blazor requires custom solutions for definitions

**Comment by breeky-dev** [comment]
Yes in a Blazor assembly app (only client side).
What do you mean by custom solutions ? (Sorry if it’s a newbie question, I’m quite new to Blazor)

Edit: sorry I get it, no SQL client side. Thank you. Do you think it would work with IndexedDB though ?

**Comment by EndGameGl** [comment]
Afaik Blazor doesn't support SQLite, my sqlite lib utilises disk space to store definitions as well, which isn't possible in browser

By custom solution I mean creating new `IDefinitionProvider` which would utilise something like IndexedDB internally
You can register your own definition provider with 
```
DefinitionProvider.Use<YourDefinitionProvider, YourDefinitionProviderConfigClass>((config) => { });
```

**Comment by breeky-dev** [comment]
I’ll look into it. Thank you!

**Comment by breeky-dev** [comment]
I can't seem to find where you pass the other interfaces to the SQLiteDefintionProvider. Its constructor takes the following arguments: 
```
public SqliteDefinitionProvider(
        IBungieClientConfiguration bungieClientConfiguration,
        SqliteDefinitionProviderConfiguration configuration,
        ILogger<SqliteDefinitionProvider> logger,
        IBungieNetJsonSerializer serializer,
        IDestiny2MethodsAccess destiny2MethodsAccess,
        IDotNetBungieApiHttpClient httpClient,
        IDefinitionAssemblyData assemblyData)
    {
          ...
     }
```
Where could I specify which interfaces I can pass to a possible constructor of IndexedDBDefinitionProvider ?
My goal is to understand how I can inject in the Definitionprovider the IJSRuntime service to manage an IndexedDB with JS (needed).
Thanks

**Comment by EndGameGl** [comment]
@samuel-chp all classes here are constructed by DI container, based of constructor arguments
Just pass all required services into constructor in same fashion `SqliteDefinitionProvider` does it

**Comment by breeky-dev** [comment]
Perfect thanks!
